Enable renaming of navigation and reference properties
ErikEJ/EFCorePowerTools pull request #1565
Opened 2022-11-01 19:23 UTC by ErikEJ

related to #211

fixes #1562

2022-11-01 19:36 UTC, ErikEJ commented on src/GUI/Shared/Extensions/ProjectExtensions.cs
> +            const string efptRenamingNavJson = "efpt.refrenaming.json";
@R4ND3LL Notice new file name

2022-11-01 20:24 UTC, R4ND3LL commented on src/GUI/Shared/Helpers/RoslynEntityPropertyRenamer.cs
> +            var rulesList = RenamingRulesSerializer.TryRead(rulesText);
TryRead is expecting a path here.  Pass "path" instead of "rulesText" and remove previous line

2022-11-01 20:28 UTC, R4ND3LL requested changes
I made one comment about the usage of TryRead in RoslynEntityPropertyRenamer.   this should be updated

2022-11-02 06:27 UTC, ErikEJ commented
I think it is a bit odd to use names like "Table" and "Column" in the json file here, but I will try to merge this now, after some smoke testing, and then consider once it has beeen tested more.

2022-11-02 06:40 UTC, ErikEJ commented
Instead of this:

```json
[
  {
    "SchemaName": "dbo",
    "Tables": [
      {
        "Columns": [
          {
            "Name": "Picture",
            "NewName": "Image"
          }
        ],
        "Name": "Categories",
        "NewName": "Categories"
      }
    ],
    "UseSchemaName": false
  }
]
```

something like this?

```json
[
  {
    "Class": [
      {
        "Properties": [
          {
            "Name": "Picture",
            "NewName": "Image",
            "Alternatename": "abc"
          }
        ],
        "Name": "Categories"
      }
    ]
  }
]

```

2022-11-02 07:18 UTC, merged

2022-11-02 12:46 UTC, R4ND3LL commented
Yes, that makes sense (using class/properties terminology).   Would just need a separate model.

To be a little pedantic, the file name "efpt.refrenaming.json" kind of suggests that it will only rename "references" as opposed to using the term nav or navigations, which includes references & collections.   

To take that a step further, technically this file can accomplish ANY property renaming so if someone wanted to use this file alone they could include all properties in it.  From that perspective, the first rule file is more of an "in-generation level renaming" whereas the new file is "post-generation renaming".   You could use that concept in the name of the file instead of "ref" (ex. post-gen-renaming).

Do you intend to move this to a command line-level library?  Hit a roadblock with that?

2022-11-02 13:02 UTC, ErikEJ commented
Please consider all this experimental at the moment...

>> the file name "efpt.refrenaming.json" kind of suggests that it will only rename "references"

Yes, a new model and a better name - maybe "efpt.propertyrenaming.json"?

>> Do you intend to move this to a command line-level library? Hit a roadblock with that?

Ideally, yes, but this will require the package install to also be executed by the command line tool. 
Which could cause headaches (it is not aware of the VS package sources)

I have created https://github.com/ErikEJ/EFCorePowerTools/issues/1567

Looking forward to hearing more testing feedback from you!

2022-11-02 14:33 UTC, R4ND3LL commented
Test passed.  Renamed nav properties in target classes as well as Configuration references.
Project builds.. it all looks good

2022-11-02 14:43 UTC, R4ND3LL commented
"efpt.property-renaming.json" is good (with hyphenation to make it more readable like "dotnet-tools.json")