Add Korean translation
ErikEJ/EFCorePowerTools pull request #2403
Opened 2024-06-17 17:39 UTC by KOZ39

This is the initial Korean translation for this project.

We discovered your post on [X](https://x.com/erikej/status/1802290415778902087) seeking someone to translate this project in Korean. Although we have no experience with EFCore, we noticed that the issue has been open for almost four months, awaiting a Korean translation.

Therefore, we decided to contribute by providing this initial translation.

Please note that this is a rough translation, and you may want to request other Korean speakers to review it.

[#2034 ](https://github.com/ErikEJ/EFCorePowerTools/issues/2034)

2024-06-17 17:50 UTC, preco21 commented
Apparently, there's another translation contribution for the Korean language (timing was sharp): https://github.com/ErikEJ/EFCorePowerTools/pull/2404

Maybe we/he can merge the translations into one PR, possibly with cross-checking and choosing better words for expression?

2024-06-17 18:49 UTC, ErikEJ commented
@preco21 Please coordinate with the other PR if possible?

2024-06-17 19:58 UTC, domicmeia commented
Just reviewed your translation, and it looks great overall! There are just a few quirks in the terminology used for the **CompareLocale.ko.resx** file. Sticking with my translations for that specific file might ensure everything aligns perfectly.

2024-06-18 02:37 UTC, preco21 commented
@ErikEJ Sure, I will review the other competing PRs and reach out to the authors to see if we can merge their work into this PR.

2024-06-18 02:41 UTC, preco21 commented
@domicmeia Hi, thank you for your review!

I appreciate your feedback and the work you've put into the translations. We'll incorporate your translations for the `CompareLocale.ko.resx` file as soon as I have time.

2024-06-18 16:16 UTC, ErikEJ commented
So this PR is ready for my review and merge now?

2024-06-18 16:45 UTC, preco21 commented
@ErikEJ Hi, I just asked the author of the other [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/2405) for the last piece of the puzzle.

If he's willing to participate in this PR, it might be best to wait for another day at this moment. (KST?)

2024-06-18 17:02 UTC, ErikEJ commented
I will wait, no rush!

2024-06-20 09:16 UTC, LocketGoma commented
Is there anything that hasn't been translated? I Want to support if i can. 
@preco21 @ErikEJ

2024-06-20 09:25 UTC, preco21 commented
@LocketGoma Hi, this PR includes all entries that needed to be translated up to this commit: bdffceb3466dad699c7f5fb97475b71758e1fdf7.

It might be missing some entries if there have been updates after this point.

We would greatly appreciate it if you could review the changes in this [PR](https://github.com/ErikEJ/EFCorePowerTools/pull/2403/files), particularly for any quirks or unsound translations.

I'm not sure if anyone have a permission to leave a code review for any PR like this, please use GitHub's code review feature and let me know if it doesn't work.

2024-06-20 09:30 UTC, LocketGoma commented
Got it. Thanks.

2024-06-20 09:35 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/AboutLocale.ko.resx
> +    The primary goals of this format is to allow a simple XML format
너무 기계 번역 같습니다.
`이 포멧의 주요 목표는 대부분의 사람이 읽을 수 있는 형식의 간단한 XML 포멧을 허용하는것입니다.
다양한 데이터 타입에 대한 생성 및 구문 분석은 데이터타입과 연관된 TypeConverter Class를 통해 수행됩니다.`
로 제안드립니다.

2024-06-20 09:36 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/AboutLocale.ko.resx
> +    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
(Write by Native Korean)
번역 되면 안되는 사항이 번역되었습니다.

`<data name="Color1" type="System.Drawing.Color, System.Drawing">파란색</data>`

2024-06-20 09:50 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>커스텀 연결 추가</value>
(Witten by Korean)
해당 부분은 위의 커스텀 AdHoc 연결과 동일한 문구여서 (원본도 그런거같은데) 사용자에게 있어 오해를 사게 할 수 있을것같습니다.
`커스텀 데이터베이스 연결 추가` 로 변경하는게 좋지 않을까요?

@ErikEJ 
I think this console message is something wrong, 
"AddAdhocConnection"'s Message And "AddAdhocDatabaseConnection" 's Message are Same.
Is it Intended Message? if not. i think should set a diffrence.

2024-06-20 09:51 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>'확장' 출력창에서 문제 내용을 확인하세요.</value>
(Witten by Korean)
'확장' 출력창에서 문제 내용을 확인하세요. 대신
`'확장' 출력창에서 에러 내용을 확인하세요.` 로 제안드립니다.

2024-06-20 09:55 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/VSPackage.ko.resx
> +    <value>일반</value>
(Witten by Korean)
타 언어 번역을 보니 "전체" / " 전부" 등으로 번역하고 있습니다.
한국어로는 "일반적인" 으로 번역했고, 타 언어는 "전반적인" 으로 본거 같아요.

2024-06-20 10:01 UTC, ErikEJ commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>커스텀 연결 추가</value>
It is intended to be the same, need to do some clean up - will do that in a future PR

2024-06-20 10:03 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>커스텀 연결 추가</value>
Thanks to Check!

2024-06-20 10:05 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/VSPackage.ko.resx
> +    <value>일반</value>
@ErikEJ "General" 's mean is 
1. (like) Common
2. (like) Entire
?

We (Ko) are Translate by "Common", but Other Locale are "Entire"

2024-06-20 11:40 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/VSPackage.ko.resx
> +    <value>일반</value>
@ErikEJ Thanks!

2024-06-20 12:39 UTC, preco21 commented
@LocketGoma 감사합니다! Thanks!

2024-06-20 12:42 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>'확장' 출력창에서 문제 내용을 확인하세요.</value>
안녕하세요, 저도 말씀해주신 내용이 나은 것 같습니다! cc @KOZ39

한편, 번역 전반에 걸쳐 "문제/오류"가 혼용되고 있는데 하나의 단어로 통일하는 것도 좋아보이네요...!

2024-06-20 12:42 UTC, KOZ39 commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>'확장' 출력창에서 문제 내용을 확인하세요.</value>
`에러 내용`보단 `오류 내용`은 어떨까요?

2024-06-20 12:54 UTC, preco21 commented on src/GUI/EFCorePowerTools/VSPackage.ko.resx
> +    <value>일반</value>
@LocketGoma 확인 감사합니다! 제가 이해한 것이 맞다면 "일반" 으로 유지하면 될까요?! (If I'm understanding it correctly, is it okay to leave it as-is?)

cc @KOZ39

2024-06-20 14:47 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/VSPackage.ko.resx
> +    <value>일반</value>
@preco21 
넵. @ErikEJ 님이 확인해주신 의미를 따르면 일반 유지가 맞는거 같습니다.

2024-06-20 14:48 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>'확장' 출력창에서 문제 내용을 확인하세요.</value>
괜찮을거같아요. 다른 곳에서 Error를 오류 라고 번역하기도 했으니 용어일치하는게 나을거같습니다. 
@KOZ39 
cc. @preco21

2024-06-20 14:49 UTC, LocketGoma commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>커스텀 연결 추가</value>
@preco21 추신으로 달아주신부분은 제대로 확인안하긴 했는데 제안주신대로 바꾸셔도 좋을거같아요!

2024-06-22 15:50 UTC, LocketGoma reviewed
확인 완료

2024-06-23 13:46 UTC, preco21 commented
Hi @utilForever, anything you would like to add or review changes before finalizing?

Ref: https://github.com/ErikEJ/EFCorePowerTools/pull/2405#issuecomment-2176724632

2024-06-23 14:51 UTC, utilForever requested changes
Can you check my comments? Thanks.

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/SharedLocale.ko.resx
> +    <value>오류가 발생했습니다. 자세한 내용은 "확장" 출력창의 내용을 확인하세요.</value>
```suggestion
    <value>오류가 발생했습니다. 자세한 내용은 "확장" 출력 창의 내용을 확인하세요.</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/SharedLocale.ko.resx
> +    <value>EFCore.Design {0} 버전을 설치하고 있습니다. 명령을 다시 시도해주세요.</value>
```suggestion
    <value>EFCore.Design {0} 버전을 설치하고 있습니다. 명령을 다시 시도해 주세요.</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.ko.vsct
> +          <ButtonText>T4 템플릿 추가</ButtonText>
여기 원문은 Add T4 Scaffolding Templates이던데, 스캐폴딩을 뺴도 괜찮을까요?
```suggestion
          <ButtonText>T4 스캐폴딩 템플릿 추가</ButtonText>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/CompareLocale.ko.resx
> +    <value>EFCore.SchemaCompare 설치 중입니다, 명령어를 재시도 해주세요.</value>
이게 좀 자연스러운 거 같은데, 확인 부탁드립니다.
```suggestion
    <value>EFCore.SchemaCompare 설치 중입니다. 명령을 다시 시도하세요</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/CompareLocale.ko.resx
> +    <value>연결을 추가할 수 없습니다, 지원되지 않는 공급자일 수 있습니다</value>
```suggestion
    <value>연결을 추가할 수 없습니다. 지원되지 않는 공급자일 수 있습니다</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.ko.resx
> +    <value>EF Core {0} 버전을 사용하는 경우, 미리보기 지원에 제한이 있을 수 있습니다. Microsoft.EntityFrameworkCore.Design preview 버전을 수동으로 설치하여 이슈 해소를 시도해볼 수 있습니다.</value>
영문에는 '이슈 해소를 시도해볼 수 있습니다'가 없던데, 어떤 이유로 추가된 걸까요?
```suggestion
    <value>EF Core {0} 버전을 사용하는 경우, 미리보기 지원에 제한이 있을 수 있습니다. Microsoft.EntityFrameworkCore.Design preview 버전을 수동으로 설치해볼 수 있습니다.</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>수동으로 데이터베이스 연결을 정의합니다.</value>
```suggestion
    <value>수동으로 정의된 연결 추가</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>'확장' 출력창에서 오류 내용을 확인하세요.</value>
```suggestion
    <value>'확장' 출력 창에서 오류 내용을 확인하세요.</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>'확장' 출력창에서 경고 내용을 확인하세요.</value>
```suggestion
    <value>'확장' 출력 창에서 경고 내용을 확인하세요.</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>템플릿을 사용하여 코드 커스텀하기</value>
```suggestion
    <value>템플릿을 사용하여 코드 커스터마이징하기</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>DbContext 경로 (f.ex. Data) - 선택사항</value>
```suggestion
    <value>DbContext 경로 (예. Data) - 선택사항</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>EntityTypes 경로 (f.ex. Models) - 선택사항</value>
```suggestion
    <value>EntityTypes 경로 (예. Models) - 선택사항</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>EF Core 패키지 설치 중</value>
```suggestion
    <value>EF Core 공급자 패키지 설치 중</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>엔티티 클래스에서 기본 생성자 제거 (실험적)</value>
영문명에 default가 없는데, '기본'이 추가된 이유가 있을까요?
```suggestion
    <value>엔티티 클래스에서 생성자 제거 (실험적)</value>
```

2024-06-23 14:51 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>이 항목을 선택하지 않으면 관련된 파일이 삭제될 수 있습니다.</value>
```suggestion
    <value>이 항목을 선택하지 않을 경우 관련된 파일이 삭제될 수 있습니다.</value>
```

2024-06-23 15:56 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/SharedLocale.ko.resx
> +    <value>오류가 발생했습니다. 자세한 내용은 "확장" 출력창의 내용을 확인하세요.</value>
감사합니다!

2024-06-23 16:09 UTC, preco21 commented on src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.ko.vsct
> +          <ButtonText>T4 템플릿 추가</ButtonText>
말씀하신대로 원문을 따라가는게 맞을 것 같습니다! 약간의 의역을 섞는 과정에서 놓친 것 같네요! 감사합니다~

2024-06-23 16:11 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/CompareLocale.ko.resx
> +    <value>EFCore.SchemaCompare 설치 중입니다, 명령어를 재시도 해주세요.</value>
저도 이게 나은 것 같습니다! 피드백 감사합니다~

2024-06-23 16:15 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>엔티티 클래스에서 기본 생성자 제거 (실험적)</value>
앗, 별다른 이유는 없고 의역하여 맥락을 풀어쓰는 과정에서 추가된 것 같습니다. 제안주신 내용으로 진행하면 될 것 같습니다!

2024-06-23 16:18 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>수동으로 데이터베이스 연결을 정의합니다.</value>
이 부분은 의도적으로 의역을 진행했는데요, 아래 스레드에서 논의가 진행되었는데, 확인하시고 피드백주시면 감사하겠습니다!

> https://github.com/ErikEJ/EFCorePowerTools/pull/2403#discussion_r1647308369

2024-06-23 16:20 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.ko.resx
> +    <value>EF Core {0} 버전을 사용하는 경우, 미리보기 지원에 제한이 있을 수 있습니다. Microsoft.EntityFrameworkCore.Design preview 버전을 수동으로 설치하여 이슈 해소를 시도해볼 수 있습니다.</value>
이것도 원문 그대로를 직역할 경우 맥락 전달이 모호한 것 같아, 맥락을 풀어서 의역하는 과정에서 추가된 것 같습니다.

내용을 원문과 동일하게 가져가는 것이 좋을까요?

2024-06-23 16:26 UTC, preco21 commented
@utilForever Thank you for your thoughtful review! I have incorporated your suggestions and left some comments where I would like to discuss further.

Once all these ongoing conversations are resolved, I will notify the owner that the PR is ready.

2024-06-23 16:34 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>수동으로 데이터베이스 연결을 정의합니다.</value>
데이터 이름에 Adhoc이 있는 걸 봐서는 '특별한 목적을 위한' 데이터베이스 연결을 추가하는 걸로 보이고, 기존 번역과 제안된 번역 모두 가능해 보입니다. 제 생각에는 다음을 기준으로 결정하면 될 거 같습니다.
"Add Custom Connection" 버튼을 눌렀을 때 (파일 추가가 아닌) 설정 창이 나타난다면 "정의한다"는 표현에 좀 더 부합하므로 기존 번역으로 넣고, 파일 추가 창만 나타난다면 "추가한다"는 표현에 좀 더 부합하므로 제안한 번역으로 넣는 게 어떨까 합니다. 의견 있으시면 자유롭게 주세요.

2024-06-23 16:36 UTC, utilForever commented on src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.ko.resx
> +    <value>EF Core {0} 버전을 사용하는 경우, 미리보기 지원에 제한이 있을 수 있습니다. Microsoft.EntityFrameworkCore.Design preview 버전을 수동으로 설치하여 이슈 해소를 시도해볼 수 있습니다.</value>
`이 경우, ~ 버전을 수동으로 설치해 보세요.` 또는 `이 경우, ~ 버전을 수동으로 설치해 보시기 바랍니다.` 정도의 표현은 어떨까요?

2024-06-25 11:25 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.ko.resx
> +    <value>EF Core {0} 버전을 사용하는 경우, 미리보기 지원에 제한이 있을 수 있습니다. Microsoft.EntityFrameworkCore.Design preview 버전을 수동으로 설치하여 이슈 해소를 시도해볼 수 있습니다.</value>
좋은 것 같습니다! 다음으로 반영해두겠습니다!

“이 경우, ~ 버전을 수동으로 설치해 보세요.“

2024-06-25 17:16 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ModelAnalyzerLocale.ko.resx
> +    <value>EF Core {0} 버전을 사용하는 경우, 미리보기 지원에 제한이 있을 수 있습니다. Microsoft.EntityFrameworkCore.Design preview 버전을 수동으로 설치하여 이슈 해소를 시도해볼 수 있습니다.</value>
https://github.com/ErikEJ/EFCorePowerTools/pull/2403/commits/d57e376182d114429e2059b8ca6b2c66cb786a85 에서 반영했습니다.

2024-06-25 17:19 UTC, preco21 commented on src/GUI/EFCorePowerTools/Locales/ReverseEngineerLocale.ko.resx
> +    <value>수동으로 데이터베이스 연결을 정의합니다.</value>
프로젝트 내에 있는 스크린샷을 참조해봤습니다: https://github.com/ErikEJ/EFCorePowerTools/blob/f851372f71c272a5865bcd028d9850c8e0fdf12d/img/efcreveng5.png

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4936201/5d38b46e-aac0-491c-a5b6-b98528f8eb26)

별도의 다이얼로그 설정 창이 나타나는 것으로 보여서 일단 기존 번역으로 유지하겠습니다!

피드백 감사합니다~

2024-06-25 17:21 UTC, preco21 commented
Hi @ErikEJ, it's a bit late, but I didn't expect so many people to get involved and help us out 😅.

Now the PR is ready to go.

Thanks.

2024-06-25 17:55 UTC, ErikEJ commented
@preco21 Thanks, what an amazing community effort! This extension is now localized in all available Visual Studio languages!

2024-06-25 18:28 UTC, merged

2024-06-26 06:09 UTC, ErikEJ commented
![image](https://github.com/ErikEJ/EFCorePowerTools/assets/4169187/a539c729-041d-4a9e-9e5e-a35d3e36807e)

2024-06-26 12:27 UTC, justinyoo commented
I really appreciate everyone involved into this Korean localisation. I'm really glad and proud to be witnessing this collaboration.

Thanks @ErikEJ for providing this awesome tool, and
thanks @preco21 @KOZ39 @domicmeia @LocketGoma @utilForever for showing your enthusiasm and efforts for this Korean localisation!