Add treeview grouping to database objects
ErikEJ/EFCorePowerTools pull request #609
Opened 2020-11-25 15:45 UTC by sm15455

Things I have done:

- Added an ObjectType Views.
- Edited reverse engineering code to detect views
- Created a ViewModel that handles database objects treeview
- Created a ViewModel that handles root nodes ("table", "Views", "Stored procedures", "Functions")

Some methods in PickTablesViewModels now redirect to the first ViewModel.

2020-11-25 16:20 UTC, ErikEJ commented
Wauw, thats a lot of changes!

How are tables without primary keys displayed?

2020-11-25 16:24 UTC, sm15455 commented
That's not changed. The icon with the yellow alert triangle.

2020-11-25 16:26 UTC, ErikEJ requested changes

2020-11-25 16:26 UTC, ErikEJ commented on src/GUI/EFCorePowerTools/Dialogs/PickTablesDialog.xaml.cs
> +
Was this intentional?

2020-11-25 16:26 UTC, ErikEJ commented on src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
> +            //foreach (var t in Tables)
Remove ?

2020-11-25 16:26 UTC, ErikEJ commented on src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
> +            //foreach (var t in Tables)
Remove?

2020-11-25 16:26 UTC, ErikEJ commented on src/GUI/EFCorePowerTools/ViewModels/PickTablesViewModel.cs
> +            //Tables.Clear();
Remove

2020-11-25 16:26 UTC, ErikEJ commented on src/GUI/RevEng.Shared/ObjectType.cs
> +        View
View = 3,

2020-11-25 16:37 UTC, ErikEJ commented
Looks good, only test update is missing now

2020-11-26 10:59 UTC, sm15455 commented
I have fixed all tests and created new ones. I have tested UI and couldn't find bugs nor reproduce #612 .

2020-11-26 12:54 UTC, ErikEJ approved these changes

2020-11-26 12:55 UTC, merged

2020-11-26 12:55 UTC, ErikEJ commented
Fantastic! I will update the command line tool asap

2020-11-26 13:15 UTC, ErikEJ commented
Hmmm... Getting a blank screen with no table after getting latest master, and updating tool? @sm15455

2020-11-26 13:22 UTC, sm15455 commented
I'm investigating. I'll fix as I finish debugging.

2020-11-26 13:25 UTC, ErikEJ commented
Looks like some data binding issue, it just shows a blank screen here, and the tables dto is populated ok:

    var pickTablesResult = ptd.ShowAndAwaitUserResponse(true);

2020-11-26 13:48 UTC, sm15455 commented
Committed fix to this branch. If it's a problem, I'll create a new PR.

2020-11-26 13:49 UTC, ErikEJ commented
This is already merged, please create new PR, thanks